// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmrnsznbixnlavtjhcpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtcm5zem5iaXhubGF2dGpoY3BpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNzc1NzMsImV4cCI6MjA3MTk1MzU3M30.kQB0KpJedVX1xdzxIcMcGj6YXp9_KJHEuw-TFCal0ao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});